# Generated by Django 5.1.3 on 2024-12-02 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WTC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('lang', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('district_corporation', models.CharField(blank=True, max_length=100, null=True)),
                ('taluka_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('village_area', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('asr_data_link', models.TextField(blank=True, null=True)),
                ('lo_sc', models.TextField(blank=True, null=True)),
                ('sentiment_cal_gra', models.TextField(blank=True, null=True)),
                ('sentiment_cal_pol', models.TextField(blank=True, null=True)),
                ('depr_rout', models.TextField(blank=True, null=True)),
                ('pending', models.BooleanField(blank=True, null=True)),
                ('lo_sc_hu', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
