# Generated by Django 5.1.3 on 2024-12-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('wtc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtc',
            name='data_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.data'),
        ),
    ]
