# Generated by Django 5.1.3 on 2024-12-02 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrutinyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_succ', models.BooleanField(default=False)),
                ('api_hit', models.IntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrutiny_data', to='base.data')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
