# Generated by Django 5.1.3 on 2024-12-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrutiny', '0003_scrutinyrecord_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrutinyrecord',
            name='scrutiny_decision',
            field=models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Reject', 'Reject')], max_length=20, null=True),
        ),
    ]
