# Generated by Django 5.1.3 on 2024-11-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentdata',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sentimentdata',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
