# Generated by Django 5.1.3 on 2024-11-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('audio_path', models.FileField(upload_to='audio_files')),
                ('text', models.TextField()),
                ('etext', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
