# Generated by Django 5.1.3 on 2024-11-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wtc',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='wtc',
            name='type',
            field=models.TextField(default='Grievance'),
            preserve_default=False,
        ),
    ]
