# Generated by Django 5.1.3 on 2024-11-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtc', '0002_rename_content_wtc_message_wtc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtc',
            name='asr_data_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
