# Generated by Django 5.1.3 on 2024-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtc', '0006_alter_wtc_address_alter_wtc_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtc',
            name='lo_sc_hu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wtc',
            name='pending',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
