# Generated by Django 5.1.3 on 2024-11-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtc', '0007_wtc_lo_sc_hu_wtc_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtc',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
