# Generated by Django 5.1.3 on 2024-12-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtc', '0010_alter_wtc_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtc',
            name='lo_sc_hu',
            field=models.TextField(blank=True, default='Accept', null=True),
        ),
        migrations.AlterField(
            model_name='wtc',
            name='pending',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
