# Generated by Django 5.1.3 on 2024-12-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtc', '0011_alter_wtc_lo_sc_hu_alter_wtc_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wtc',
            old_name='lo_sc_hu',
            new_name='lo_sc_mach',
        ),
    ]
