# Generated by Django 5.1.3 on 2024-12-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtc', '0012_rename_lo_sc_hu_wtc_lo_sc_mach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wtc',
            old_name='lo_sc_mach',
            new_name='lo_sc_hu',
        ),
    ]
