# Generated by Django 5.1.3 on 2024-12-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtc', '0013_rename_lo_sc_mach_wtc_lo_sc_hu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtc',
            name='lo_sc_hu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
