# Generated by Django 5.1.3 on 2024-12-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtc', '0014_alter_wtc_lo_sc_hu'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtc',
            name='is_posted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
