# Generated by Django 5.1.3 on 2024-12-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtc', '0015_wtc_is_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtc',
            name='depr_rout_fetch_first',
            field=models.TextField(blank=True, null=True),
        ),
    ]
