# Generated by Django 5.1.3 on 2024-11-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtc', '0003_wtc_asr_data_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtc',
            name='depr_rout',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wtc',
            name='lo_sc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wtc',
            name='sentiment_cal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
